# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M669iZEr086ye0SjsOp60Xfk6R5WkwW
"""

a=int(input())
b=int(input())
c=int(input())
total=a+b+c
if(total>50):print(total-total/10)
else:print(total)